linters:
  disable:
    - gochecknoglobals
    - lll
    - unused
    - wsl
    - gomnd
    - testpackage
    - nolintlint
    - godox
    - misspell
    - maligned
  enable-all: true
linters-settings:
  goimports:
    local-prefixes: github.com/radianceteam/ton-client-go

