linters:
  disable:
    - gochecknoglobals
    - lll
    - unused
    - wsl
    - gomnd
    - testpackage
    - nolintlint
    - maligned
    - goerr113
    - nlreturn
    - exhaustivestruct
    - wrapcheck
    - paralleltest
    - forbidigo
    - cyclop
  enable-all: true
linters-settings:
  goimports:
    local-prefixes: github.com/radianceteam/ton-client-go

