linters:
  disable:
    - gochecknoglobals
    - lll
    - unused
    - wsl
    - gomnd
    - testpackage
    - nolintlint
    - maligned
    - goerr113
    - nlreturn
    - exhaustivestruct
    - wrapcheck
    - paralleltest
    - forbidigo
    - cyclop
    - tagliatelle
    - golint
    - scopelint
    - interfacer
    - varnamelen
    - errchkjson
    - gci
    - forcetypeassert
    - exhaustruct
  enable-all: true
linters-settings:
  goimports:
    local-prefixes: github.com/radianceteam/everscale-client-go

