version: '2'

tasks:
  coverage:
    desc: 'Run tests with coverage and open report in default browser'
    cmds:
      - go test -coverpkg=./... -coverprofile=./tmp/cover.out ./...
      - go tool cover -html=./tmp/cover.out -o ./tmp/cover.html
      - open ./tmp/cover.html
  attach_hooks:
    desc: "Attaches git hooks"
    cmds:
      - cp ./tools/prepare-commit-msg.sh ./.git/hooks/prepare-commit-msg
      - cp ./tools/pre-commit.sh ./.git/hooks/pre-commit
      - cp ./tools/pre-push.sh ./.git/hooks/pre-push
      - chmod 777 ./.git/hooks/prepare-commit-msg
      - chmod 777 ./.git/hooks/pre-commit
      - chmod 777 ./.git/hooks/pre-push
  lint:
    desc: "Run linter"
    cmds:
      - golangci-lint run ./...
  generate:
    desc: "Generates code by json spec"
    cmds:
      - go run ./cmd/gen
      - go fmt ./client/*.gen.go
      - goimports -w ./client/*.gen.go
      - golangci-lint run --fix ./client/
  download_sdk:
    desc: "Downloads SDK"
    cmds:
      - rm -rf ./tmp/libton_client.*
      - wget https://binaries.tonlabs.io/tonclient_1_{{OS}}.gz -O ./tmp/libton_client.{{if eq OS "darwin"}}dylib{{else}}so{{end}}.gz
      - gzip -d ./tmp/*.gz
      - chmod 777 ./tmp/libton_client.*
  run:
    desc: "Run in host system without container"
    cmds:
      - go run ./cmd/cli
  test:
    desc: "Run tests"
    cmds:
      - go test -tags without_local_ton_node ./...
  full_test:
    desc: "Run tests with local ton node"
    cmds:
      - go test ./...
