name: CI
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: download-dylibs
        run: ./tools/download-sdk-ci.sh
        shell: sh
      - name: Run TON node
        run: docker run -d --name local-node -p80:80 tonlabs/local-node:0.33.0
      - name: Test
        env:
          CGO_LDFLAGS: '-L/tmp/ -lton_client'
          LD_LIBRARY_PATH: '/tmp/'
        run: go test ./...
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download-dylibs
        run: ./tools/download-sdk-ci.sh
        shell: sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        env:
          CGO_LDFLAGS: '-L/tmp/ -lton_client'
        with:
          version: v1.52.2
